# Generated by Django 3.1.3 on 2020-11-23 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_placed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
    ]
