# Generated by Django 3.1.3 on 2020-11-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_prep',
            new_name='prep_time',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_placed',
            new_name='time_placed',
        ),
    ]
